helloapp:
  saying: Guten Tag aus
management:
  endpoints:
    web:
      exposure:
        include: '*'
greeting:
  saying: Hola Spring Boot
  backendServiceHost: localhost
  backendServicePort: 8080
server:
  port: 9090